# Generated by Django 6.0.3 on 2026-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
